In [6]:
import pandas as pd
import numpy as np
data = pd.read_csv('data-001.csv')

dataset = np.load('../datasets/v0_eigens.npz')
train_eigens = dataset['train_eigens'][:, :-28]
train_labels = dataset['train_eigens'][:, -28:]

## find user with most activity in raw data

In [2]:
data.groupby('user_id').size().sort_values(ascending=False).head()

user_id
1092    74900
722     72382
148     22755
323     21693
1089    18902
dtype: int64

In [3]:
data[data["user_id"] == 1092].head()

user_id  device_id  session_id  title_id               event_time  \
969735     1092       2305      103289       120  2017-01-02 09:45:14.420   
969736     1092       2305      103289       120  2017-01-02 09:46:34.898   
969737     1092       2305      103289       120  2017-01-02 09:47:01.923   
969738     1092       2305      103289       120  2017-01-02 09:47:26.847   
969739     1092       2305      103289       120  2017-01-02 09:49:02.516   

        played_duration action_trigger platform  episode_number  \
969735                4          leave      Web              64   
969736               73           seek      Web               1   
969737               26           seek      Web               1   
969738               23           seek      Web               1   
969739               92           seek      Web               1   

        series_total_episodes_count internet_connection_type  is_trailer  
969735                          102       online but unknown       False  
969736                          102       online but unknown       False  
969737                          102       online but unknown       False  
969738                          102       online but unknown       False  
969739                          102       online but unknown       False

## a look at user #1092 in train_eigens

In [4]:
print (train_eigens[1092].sum())
train_eigens[1092]
# data-001.csv ~  data-045.csv : 訓練組使用者在 2017/01/01-00:00:00 ~ 2017/08/21-01:00:00 間的使用記錄。

197.0


array([0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1.,
       1., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0.,
       0., 1., 1., 1., 0., 0., 1., 0., 1., 1., 1., 0., 0., 0., 1., 1., 0.,
       0., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1.,
       0., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 1.,
       1., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1.,
       0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.,
       1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [7]:
print (train_labels[1092].sum())
train_labels[1092]
#time_slot_0 : 使用者在 2017/08/14-01:00:00 ~ 2017/08/14-09:00:00 間有無活動（機率）。
#time_slot_1 : 使用者在 2017/08/14-09:00:00 ~ 2017/08/14-17:00:00 間有無活動（機率）。
#time_slot_2 : 使用者在 2017/08/14-17:00:00 ~ 2017/08/14-21:00:00 間有無活動（機率）。
#time_slot_3 : 使用者在 2017/08/14-21:00:00 ~ 2017/08/15-01:00:00 間有無活動（機率）。
#time_slot_4 ~ time_slot_27 : 以此類推。

2.0


array([0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
data_1092 = data[data["user_id"] == 1092]
data_1092.head()

user_id  device_id  session_id  title_id               event_time  \
969735     1092       2305      103289       120  2017-01-02 09:45:14.420   
969736     1092       2305      103289       120  2017-01-02 09:46:34.898   
969737     1092       2305      103289       120  2017-01-02 09:47:01.923   
969738     1092       2305      103289       120  2017-01-02 09:47:26.847   
969739     1092       2305      103289       120  2017-01-02 09:49:02.516   

        played_duration action_trigger platform  episode_number  \
969735                4          leave      Web              64   
969736               73           seek      Web               1   
969737               26           seek      Web               1   
969738               23           seek      Web               1   
969739               92           seek      Web               1   

        series_total_episodes_count internet_connection_type  is_trailer  
969735                          102       online but unknown       False  
969736                          102       online but unknown       False  
969737                          102       online but unknown       False  
969738                          102       online but unknown       False  
969739                          102       online but unknown       False

## event_time is in str format, convert to datetime

In [9]:
data_1092.event_time.iloc[1] #data['event_time'][1]

'2017-01-02 09:46:34.898'

In [11]:
data_1092['event_time'] = pd.to_datetime(data_1092['event_time'])

data_1092.event_time.iloc[1]

/home/taipeifx/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


Timestamp('2017-01-02 09:46:34.898000')

### split datetime to date and time columns

In [13]:
data_1092['date'] = [d.date() for d in data_1092['event_time']]
data_1092['time'] = [d.time() for d in data_1092['event_time']]

data_1092.head()

/home/taipeifx/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/home/taipeifx/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


user_id  device_id  session_id  title_id              event_time  \
969735     1092       2305      103289       120 2017-01-02 09:45:14.420   
969736     1092       2305      103289       120 2017-01-02 09:46:34.898   
969737     1092       2305      103289       120 2017-01-02 09:47:01.923   
969738     1092       2305      103289       120 2017-01-02 09:47:26.847   
969739     1092       2305      103289       120 2017-01-02 09:49:02.516   

        played_duration action_trigger platform  episode_number  \
969735                4          leave      Web              64   
969736               73           seek      Web               1   
969737               26           seek      Web               1   
969738               23           seek      Web               1   
969739               92           seek      Web               1   

        series_total_episodes_count internet_connection_type  is_trailer  \
969735                          102       online but unknown       False   
969736                          102       online but unknown       False   
969737                          102       online but unknown       False   
969738                          102       online but unknown       False   
969739                          102       online but unknown       False   

              date             time  
969735  2017-01-02  09:45:14.420000  
969736  2017-01-02  09:46:34.898000  
969737  2017-01-02  09:47:01.923000  
969738  2017-01-02  09:47:26.847000  
969739  2017-01-02  09:49:02.516000

In [14]:
print (type(data_1092.date.iloc[1]))
print (type(data_1092.time.iloc[1]))

<class 'datetime.date'>
<class 'datetime.time'>


## sort into time slots

In [ ]:
#time_slot_0 : 使用者在 01:00:00 ~ 09:00:00 間有無活動（機率）。
#time_slot_1 : 使用者在 09:00:00 ~ 17:00:00 間有無活動（機率）。
#time_slot_2 : 使用者在 17:00:00 ~ 21:00:00 間有無活動（機率）。
#time_slot_3 : 使用者在 21:00:00 ~ 01:00:00 間有無活動（機率）。

In [15]:
data_1092.time.iloc[1]

datetime.time(9, 46, 34, 898000)

In [35]:
from datetime import datetime, time

def is_time_between(begin_time, end_time, check_time=None):
    if begin_time < end_time:
        return int(check_time >= begin_time and check_time <= end_time)
    else: # crosses midnight
        return int(check_time >= begin_time or check_time <= end_time) #return int of boolean
    
# testing for activity in time period 1:00 ~ 9:00
for d in data_1092.time.iloc[2495:2500]:
    print (is_time_between(time(1,00), time(9,00), d))

data_1092.time.iloc[2495:2500]

1
1
0
0
0


972230    08:54:03.680000
972231    08:54:37.407000
972232    09:51:38.255000
972233    09:51:39.286000
972234    09:51:42.985000
Name: time, dtype: object

In [36]:
#time_slot_0 : 使用者在 01:00:00 ~ 09:00:00 間有無活動（機率）。
#time_slot_1 : 使用者在 09:00:00 ~ 17:00:00 間有無活動（機率）。
#time_slot_2 : 使用者在 17:00:00 ~ 21:00:00 間有無活動（機率）。
#time_slot_3 : 使用者在 21:00:00 ~ 01:00:00 間有無活動（機率）。

a = []
b = []
c = []
e = []
for d in data_1092.time:
    a.append(is_time_between(time(1,00), time(9,00), d))
    b.append(is_time_between(time(9,00), time(17,00), d))
    c.append(is_time_between(time(17,00), time(21,00), d))
    e.append(is_time_between(time(21,00), time(1,00), d))


In [37]:
data_1092['1_9'] = a
data_1092['9_17'] = b
data_1092['17_21'] = c
data_1092['21_1'] = e

/home/taipeifx/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/home/taipeifx/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
/home/taipeifx/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in 

In [38]:
#pd.options.display.max_rows=5000
data_1092

user_id  device_id  session_id  title_id              event_time  \
969735      1092       2305      103289       120 2017-01-02 09:45:14.420   
969736      1092       2305      103289       120 2017-01-02 09:46:34.898   
969737      1092       2305      103289       120 2017-01-02 09:47:01.923   
969738      1092       2305      103289       120 2017-01-02 09:47:26.847   
969739      1092       2305      103289       120 2017-01-02 09:49:02.516   
969740      1092       2305      103289       120 2017-01-02 09:54:59.376   
969741      1092       2305      103289       120 2017-01-02 09:55:07.620   
969742      1092       2305      103289       120 2017-01-02 09:56:07.076   
969743      1092       2305      103289       120 2017-01-02 09:56:16.643   
969744      1092       2305      103289       120 2017-01-02 09:56:24.718   
969745      1092       2305      103289       120 2017-01-02 09:56:41.867   
969746      1092       2305      103289       120 2017-01-02 09:56:56.034   
969747      1092       2305      103289       120 2017-01-02 09:58:35.366   
969748      1092       2305      103289       120 2017-01-02 10:00:39.001   
969749      1092       2305      103289       120 2017-01-02 10:00:45.721   
969750      1092       2305      103289       120 2017-01-02 10:12:47.217   
969751      1092       2305      103289        54 2017-01-02 10:13:13.399   
969752      1092       2305      103289        54 2017-01-02 10:25:28.683   
969753      1092       2305      103289        54 2017-01-02 10:25:31.596   
969754      1092       2305      103289        54 2017-01-02 10:25:33.313   
969755      1092       2305      103289        54 2017-01-02 10:25:35.889   
969756      1092       2305      103289        54 2017-01-02 10:25:42.237   
969757      1092       2305      103289        54 2017-01-02 10:27:13.183   
969758      1092       2305      103289        54 2017-01-02 10:32:10.458   
969759      1092       2305      103289        54 2017-01-02 10:33:02.244   
969760      1092       2305      103289        54 2017-01-02 10:35:17.946   
969761      1092       2305      103289        54 2017-01-02 10:36:42.921   
969762      1092       2305      103289        54 2017-01-02 10:36:44.236   
969763      1092       2305      103289        54 2017-01-02 10:36:45.180   
969764      1092       2305      103289        54 2017-01-02 10:36:58.620   
...          ...        ...         ...       ...                     ...   
1044605     1092       2309      103580        74 2017-08-15 04:21:10.218   
1044606     1092       2309      103580        74 2017-08-15 04:21:11.710   
1044607     1092       2309      103580        74 2017-08-15 04:21:13.981   
1044608     1092       2309      103580        74 2017-08-15 04:21:14.971   
1044609     1092       2309      103580        74 2017-08-15 04:21:16.685   
1044610     1092       2309      103580        74 2017-08-15 04:21:33.290   
1044611     1092       2309      103580        74 2017-08-15 04:21:34.186   
1044612     1092       2309      103580        74 2017-08-15 04:21:37.946   
1044613     1092       2309      103580        74 2017-08-15 04:21:39.146   
1044614     1092       2309      103580        74 2017-08-15 04:21:46.608   
1044615     1092       2309      103580        74 2017-08-15 04:21:50.889   
1044616     1092       2309      103580        74 2017-08-15 04:21:56.781   
1044617     1092       2309      103580        74 2017-08-15 04:21:59.552   
1044618     1092       2309      103580        74 2017-08-15 04:22:01.295   
1044619     1092       2309      103580        74 2017-08-15 04:22:05.365   
1044620     1092       2309      103580        74 2017-08-15 04:22:27.699   
1044621     1092       2309      103580        74 2017-08-15 04:22:28.563   
1044622     1092       2309      103580        74 2017-08-15 04:22:35.765   
1044623     1092       2309      103580        74 2017-08-15 04:22:37.235   
1044624     1092       2309      103580        74 2017-08-15 04:22:39.708   
10446

In [39]:
data_1092_group = data_1092.groupby('date')['1_9','9_17','17_21','21_1'].agg('sum')
data_1092_group.head()

1_9  9_17  17_21  21_1
date                              
2017-01-02    0   436   1207     0
2017-01-03  854  1081    486     0
2017-01-04   64   526     94     0
2017-01-05  762   215      7     0
2017-01-06   99    27      0     0

In [40]:
# taking a look at the pre-processed train_eigens data
#data_1092.groupby('date')['1_9','9_17','17_21','21_1'].agg('sum').shape : (113,4)
train_eigens[1092].reshape(224,4)

array([[0., 1., 1., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 0.],
       [1., 1., 0., 0.],
       [0., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 0.],
       [1., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 1., 1., 0.],
       [0., 1., 0., 1.],
       [1., 1., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 1., 1., 1.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 0.],


In [322]:
data_1092_group[-3:]

1_9  9_17  17_21  21_1
date                              
2017-08-13    1     0      0     0
2017-08-15  215     0      0     0
2017-08-16    1     0      0     0

In [41]:
# pre-processed train_labels data
# time_slot_0 : 使用者在 2017/08/14-01:00:00 ~ 2017/08/14-09:00:00 間有無活動（機率）。
train_labels[1092].reshape(7,4)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [42]:
data_1092_group.sum()

1_9      29994
9_17     29347
17_21    13620
21_1      1939
dtype: int64

In [43]:
# same labels also given in label-001.csv
label = pd.read_csv('label-001.csv')
label.head()

user_id  time_slot_0  time_slot_1  time_slot_2  time_slot_3  time_slot_4  \
0        0            0            0            0            0            0   
1        1            0            0            0            0            0   
2        2            0            1            0            0            0   
3        3            0            1            1            0            0   
4        4            0            0            0            0            0   

   time_slot_5  time_slot_6  time_slot_7  time_slot_8  ...  time_slot_18  \
0            0            0            0            0  ...             0   
1            0            0            0            0  ...             0   
2            0            0            0            0  ...             0   
3            0            0            0            0  ...             0   
4            0            0            0            0  ...             0   

   time_slot_19  time_slot_20  time_slot_21  time_slot_22  time_slot_23  \
0             0             1             0             0             0   
1             0             0             0             0             0   
2             0             0             0             0             0   
3             0             0             0             0             0   
4             0             0             0             0             0   

   time_slot_24  time_slot_25  time_slot_26  time_slot_27  
0             0             0             0             0  
1             0             0             0             0  
2             0             0             0             0  
3             1             1             1             0  
4             0             0             0             0  

[5 rows x 29 columns]

In [44]:
label_1092 = label[label["user_id"] == 1092].iloc[:,1:]
label_1092.as_matrix().reshape(7, 4)

/home/taipeifx/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

## create a list of dates

In [45]:
# data-001.csv ~  data-045.csv : 訓練組使用者在 2017/01/01-00:00:00 ~ 2017/08/21-01:00:00 間的使用記錄。
datelist = pd.date_range(datetime(2017,1,2), datetime(2017,8,13))# periods=100
datelist = [d.date() for d in datelist]
datelist[1:5]

[datetime.date(2017, 1, 3),
 datetime.date(2017, 1, 4),
 datetime.date(2017, 1, 5),
 datetime.date(2017, 1, 6)]

In [46]:
empty_datelist = pd.DataFrame(datelist, columns=['date'])
empty_datelist.head()

date
0  2017-01-02
1  2017-01-03
2  2017-01-04
3  2017-01-05
4  2017-01-06

In [47]:
empty_datelist.iloc[1]

date    2017-01-03
Name: 1, dtype: object

In [48]:
full_datelist = empty_datelist.merge(data_1092_group, how='left',left_on = 'date', right_on = 'date').fillna(0)
full_datelist.head()

date    1_9    9_17   17_21  21_1
0  2017-01-02    0.0   436.0  1207.0   0.0
1  2017-01-03  854.0  1081.0   486.0   0.0
2  2017-01-04   64.0   526.0    94.0   0.0
3  2017-01-05  762.0   215.0     7.0   0.0
4  2017-01-06   99.0    27.0     0.0   0.0

In [49]:
full_datelist['1_9'] = np.where(full_datelist['1_9'] > 0, 1, 0)
full_datelist['9_17'] = np.where(full_datelist['9_17'] > 0, 1, 0)
full_datelist['17_21'] = np.where(full_datelist['17_21'] > 0, 1, 0)
full_datelist['21_1'] = np.where(full_datelist['21_1'] > 0, 1, 0)

In [50]:
full_datelist.head()

date  1_9  9_17  17_21  21_1
0  2017-01-02    0     1      1     0
1  2017-01-03    1     1      1     0
2  2017-01-04    1     1      1     0
3  2017-01-05    1     1      1     0
4  2017-01-06    1     1      0     0

In [53]:
#array created from raw data
full_datelist_array = full_datelist.drop('date', axis=1).as_matrix().reshape(224, 4)
full_datelist_array[0:10]

/home/taipeifx/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([[0, 1, 1, 0],
       [1, 1, 1, 0],
       [1, 1, 1, 0],
       [1, 1, 1, 0],
       [1, 1, 0, 0],
       [0, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 0]])

In [54]:
print (full_datelist_array.shape) #from raw data
print (train_eigens[1092].reshape(224,4).shape) #from preprocessed data

#do the two arrays match?
tf = full_datelist_array == train_eigens[1092].reshape(224,4)
tf[0:10]

(224, 4)
(224, 4)


array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True, False],
       [ True,  True,  True,  True]])

In [55]:
#which rows in the raw data array and preprocessed array differ?
df_tf = pd.DataFrame(tf)

df_tf[df_tf == False].dropna(how='all')

0   1   2    3
8   NaN NaN NaN  0.0
14  NaN NaN NaN  0.0
15  NaN NaN NaN  0.0
31  NaN NaN NaN  0.0
32  NaN NaN NaN  0.0
33  NaN NaN NaN  0.0
34  NaN NaN NaN  0.0
40  NaN NaN NaN  0.0
44  NaN NaN NaN  0.0
46  NaN NaN NaN  0.0
47  NaN NaN NaN  0.0
123 NaN NaN NaN  0.0
124 NaN NaN NaN  0.0
206 NaN NaN NaN  0.0
207 NaN NaN NaN  0.0